KA <- data.frame(KeyAccount = c("WALMART DISCOUNT STO",
                          "WALMART NEIGHBORHOOD",
                          "WALMART SUPER CENTER",
                          "PUBLIX (JACKSONVILLE",
                          "PUBLIX (LAKELAND)",
                          "PUBLIX (MIAMI)",
                          "SPEEDWAY",
                          "7-ELEVEN",
                          "RACETRAC FRANCHISE",
                          "RACETRAC PETROLEUM",
                          "PUBLIX PHARMACYS",
                          "WALGREEN",
                          "DOLLAR GENERAL #1016",
                          "CVS DRUGS",
                          "FAMILY DOLLAR STORES",
                          "DOLLAR TREE STORES",
                          "BIG LOTS",
                          "FIVE BELOW"),
           `Ordering Method` = c("EDID",
                                 "EDID",
                                 "EDID",
                                 "EDI",
                                 "EDI",
                                 "EDI",
                                 "EDI",
                                 "EDI",
                                 "EDID",
                                 "EDID",
                                 "EDID",
                                 "Future EDID",
                                 "Future EDID",
                                 "Future EDID",
                                 "Future EDID",
                                 "Future EDID",
                                 "Future EDID",
                                 "Future EDID"))

channel <- data.frame(Channel = c("Convenience Store/Pe"),
                 `Ordering Method` = c("EDID"))